In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
deji= np.array([[1,2,3,4],[5,6,7,8]])
print (deji.ndim)
print (deji)

2
[[1 2 3 4]
 [5 6 7 8]]


In [9]:
threed= np.array ([[[1,2,3],[4,5,6]],[[7,8,9],[3,56,78]]])
# print(threed.ndim)
# print(threed[1,0,2])
# print(threed.shape)
for i in threed:
    for j in i:
        for m in j:
         print(m)
zerosarray= np.zeros(10)
zerosarray= zerosarray.astype(int)
print (zerosarray.shape)
print (zerosarray)


1
2
3
4
5
6
7
8
9
3
56
78
(10,)
[0 0 0 0 0 0 0 0 0 0]


In [10]:
ones= np.ones(10)
ones= ones.astype(int)
print (ones)
pf = np.full(10,6)
print(pf)

[1 1 1 1 1 1 1 1 1 1]
[6 6 6 6 6 6 6 6 6 6]


In [11]:
matrix = np.array ([[1,2,3],[4,5,6]])
add= matrix + 2
multiply= matrix *2
division= matrix/2
raisetopower= matrix **2 
Transponse= matrix.T
print (Transponse)
print (multiply)
print (division)
print (raisetopower)
print(matrix)
print(add)

[[1 4]
 [2 5]
 [3 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[ 1  4  9]
 [16 25 36]]
[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [12]:
matrix2 = np.array([[3,4,5],[6,7,8]])
Concantenante= matrix + matrix2 
print (Concantenante)

[[ 4  6  8]
 [10 12 14]]


In [13]:
m= np.array([[1,2,3],[5,7,9],[8,9,4]])
m2 = np.array ([[3,4,5],[6,7,8],[4,8,5]])
matrixmultiplication= np.matmul(m, m2)
print(matrixmultiplication)
min= np.min(m2)
max= np.max(m2)
mean = np.mean(m2)
std= np.std(m2)
print (mean)
print (max)
print (std)
print(min)

[[ 27  42  36]
 [ 93 141 126]
 [ 94 127 132]]
5.555555555555555
8
1.7069212773041351
3


In [14]:
#creating a dataframe 
mylist = [['Apple','Red'],['Banana','yellow'],['Orange','Orange']]
mylist
mydataframe = pd.DataFrame(mylist, columns = ['fruits', 'color'])
mydataframe

fruits   color
0   Apple     Red
1  Banana  yellow
2  Orange  Orange